### ISSUE TITLE
Problem with docker setup: missing `cozy-konnector-libs`

### ISSUE THREAD

**Issue by nitnelave** [konnectors/boursorama#163]
Hi,

I'm trying to set up a cozy stack with the boursorama konnector, self-hosted with docker (https://github.com/vsellier/easy-cozy). Apps seem to run fine, but when I installed this konnector (using `cozy-stack apps install` with this github url), I couldn't connect to my boursorama account.

In the logs, I got the following error: 
```
Stderr: internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module cozy-konnector-libs
Require stack:
- /tmp/konnector-boursorama567143635/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/tmp/konnector-boursorama567143635/src/index.js:1:27)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: MODULE_NOT_FOUND,
  requireStack: [ /tmp/konnector-boursorama567143635/src/index.js ]
}
```

However, the Ameli konnector (https://github.com/konnectors/cozy-konnector-ameli) uses the same cozy-konnector-libs, with the same version (4.42.0) and works fine on the same stack.

I tried asking the Cozy team for help, they told me they didn't support docker installations. I tried asking the maintainer of the docker stack for help (https://github.com/vsellier/easy-cozy/issues/9) but it seems it's not an issue of the stack since another konnector using the same lib works fine.

If there's anything I can do to help, logs to pull, anything, please tell me :)

**Comment by orandin** [comment]
Hi, 

I didn't know this stack with Docker. It's very interesting!
To install a Konnector, I recommend to use Cozy store or this command: 

`cozy-stack konnectors update <slug> [sourceurl] [flags]`

Example: 
`cozy-stack konnectors update --domain {YOUR_INSTANCE} boursorama registry://boursorama/stable`

- `registry://boursorama/stable` : will install a published release of boursorama konnector from official Cozy registry (recommended)
- `git://github.com/konnectors/boursorama.git#build` : will install a published or not release of boursorama konnector from this repository

**Comment by nitnelave** [comment]
Okay, I don't know what happened, but it worked :)

To be clear: the konnector is not available in the store (not listed), and trying to install based on the `registry://` URL didn't work (`Error: Application manifest is not reachable`), but updating with the git URL (which is how I installed it) worked, and the job worked!

You must have fixed it between the last time I tried and now :)

Thanks a lot!

**Comment by orandin** [comment]
For the issue about registry, maybe it's a configuration problem with cozy-stack. 
In your config (`/etc/cozy/cozy.yml`), do you have a `registries` field declared?

Example: https://github.com/cozy/cozy-stack/blob/master/cozy.example.yaml#L248

**Comment by nitnelave** [comment]
I didn't have a registry, but after adding the default one from the link you gave me, I still don't see Boursorama (or anything new for that matter). I get the list of utilities, insurances and so on, but not banks.

**Comment by orandin** [comment]
I checked my configuration and I have those registries:
```
registries:
  default:
  - https://apps-registry.cozycloud.cc/selfhosted
  - https://apps-registry.cozycloud.cc/banks
  - https://apps-registry.cozycloud.cc/
  ```

I think `https://apps-registry.cozycloud.cc/selfhosted` has all selfhosted konnectors such as boursorama konnector
