### ISSUE TITLE
Bug with login (code for repair)

### ISSUE THREAD

**Issue by Benoit485** [konnectors/boursorama#227]
Inside code lib.js change the start line on function

It's need to add _token and get his value from login page

`function authenticate(urlLogin, urlKeyboard, login, passwd) {
    let formData = {
        'form[clientNumber]': login,
        'form[password]': '',
        'form[matrixRandomChallenge]': '',
        'form[_token]': ''
    }

    return request({
        uri: urlLogin
    })
        .then($ => {
            const token = $('input#form__token').val()
            formData['form[_token]'] = token

            return request({
                uri: urlKeyboard
            })
        })`

**Comment by orandin** [comment]
Hi @Benoit485 

Thank you for your report and your code. I will integrate it into the Konnector and fix the issue.
Fell free to make a pull request if you detect an improvement!
