### ISSUE TITLE
Some labels should be filtered

### ISSUE THREAD

**Issue by X-dark** [konnectors/boursorama#46]
It seems the account list has some elements that should be filtered out as they are not accounts. I had to filter this but don't know how to do it properly (if filtering after the scrape operation, it will still throw a lot of error because type is not defined on those entries):

```js
filter( x => x.label != 'TOUS MES COMPTES' && x.label != '' && x.label != '. . .')
```

**Comment by X-dark** [comment]
I would have done a PR but as said above, I don't know how to filter properly to avoid the scrape function to throw errors before the filtering occurs.

**Comment by Benoit485** [comment]
I did update who work but i dont know how to put here, you can add by :

cozy-stack konnectors install --domain cloud.mewto.me boursorama 'git+https://git@gitlab.infosplatch.fr/konnectors/boursorama.git#build'
