### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Benoit485** [konnectors/boursorama#94]
Hey

I did update who work, because what Store let install not work correctly

Idk how to pull here then do :
cozy-stack konnectors install --domain cloud.mewto.me boursorama 'git+https://git@gitlab.infosplatch.fr/konnectors/boursorama.git#build'

For more info (in french) : 

Bonjour

Il manque dans helpers.js

(line ~23) const AbbrToAccountType = {

cefp: AccountType.MARKET

pour les comptes epargne piloté,

epargne: AccountType.SAVINGS

pour les livret simple (epargne/csl, juste sl est recuperer par le match)

et pour les prets : 

  consommation: AccountType.CREDIT

puis au dessus dans const AccountType = {
rajouter

  PEA: 'PEA',

  CREDIT: 'ConsumerCredit'

Et il faudrait ajouter dans lib.js, ligne ~275

// delete elems with undefined type.filter(obj => obj.type !== undefined)

sinon tous les liens sont retournée meme si ce n’est pas un compte valide, lorsqu’on agrege d’autres banque par exemple, et on obtient une erreur interne

et rajouter avant return

if (number === '') {const numberAgain = scrape($('div.account-number'), {reference: {sel: 'strong:first-child' }})account.number = numberAgain.reference account.vendorId = numberAgain.reference }}

pour permettre de recuperer le numero de compte quand il se place sous un div et non un h3

**Comment by orandin** [comment]
Hey @Benoit485! 
Thanks for your contribution, it's very appreciate :) 
Can you generate the [patch file](https://git-scm.com/docs/git-format-patch) with all your modifications? If the tests are ok, I will integrate them :) 

And if you can also provide me with the HTML pages to test : _"compte epargne piloté"_, _"livret simple"_ et _"les prets"_ (don't forget to anonymize the data :)), that would be great!

**Comment by Benoit485** [comment]
Hey @orandin 

I find how to do pull request (I'm not familiarly with git)

I think is better like this

I put file in examples/ folder for you can see about account received
I not put what it's show when we click because, for "livret simple" it's same "cav" account  and for another have no data who can be analyse and save in Cozy, it's abbout stock market

If you are ok, I will try to implement code for get files (accounts statements and other)


Thank to you for this connector and another for fortuneo too (I think I will try to implement files getting too).
